### ISSUE TITLE
Is there a real documentation page?

### ISSUE THREAD

**Issue by ali-elgabri** [FasterXML/woodstox#101]
I am having trouble finding an actual page up with documentation. There *was* codehause, but that's been obliterated years ago, so...

Hoping I could find some actual documentation!

**Comment by cowtowncoder** [comment]
Actual documentation about... ? Woodstox implements Stax and SAX APIs, so most of the functionality is available through those interfaces.

Aside from that, have you looked at wiki of this repo?

https://github.com/FasterXML/woodstox/wiki

**Comment by ali-elgabri** [comment]
Well, an explanation of what WoodStox does differently and why it's better would perhaps be a good start? How to set it up, etc? I mean I have a set up working but it took some time to figure it out. 

I've taken a look at that page, yeah, but it wasn't very informative.

**Comment by kupci** [comment]
How about this:

>     it's faster
>     has extra features
>     it's more mature and well maintained

https://courses.baeldung.com/courses/27917/lectures/423862

**Comment by cowtowncoder** [comment]
@ali-elgabri True, old Codehaus repo had probably more description. I would be happy to merge a PR for README, or if you wanted to contribute to Wiki (based on what you find) give access.

And yes, @kupci is right: I would probably also add "more standards-compliant", especially regarding very strict XML compliancy via XMLTest -- the only Java parser beside Xerces to get to 99% pass rate (most parsers struggle to get past ~50%). I think test suite was from here: https://www.w3.org/XML/Test/ but it has been a while since I ran it (I think it requires use of SAX API).
