### ISSUE TITLE
Problems using woodstox java 11

### ISSUE THREAD

**Issue by pavan2017** [FasterXML/woodstox#111]
I have upgraded from java 8 to 11 and using woodstox 4.1.

```
public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) {
        try {
            XMLValidationSchemaFactory factory = XMLValidationSchemaFactory.newInstance(XMLValidationSchema.SCHEMA_ID_W3C_SCHEMA);
            XMLValidationSchema xmlValidationSchema = factory.createSchema(schemaResource.getURL());
            XMLInputFactory2 xmlFactory = (XMLInputFactory2) XMLInputFactory2.newInstance();
            InputStream xmlInputStream = xmlResource.getInputStream();
            XMLStreamReader2 reader = (XMLStreamReader2) xmlFactory.createXMLStreamReader(xmlInputStream);
            reader.validateAgainst(xmlValidationSchema);
            while (reader.hasNext()) {
                int eventType = reader.next();
            
            }
          } catch (Exception e) {
            throw new IllegalArgumentException("Error while validating " + xmlResource.getFilename(), e);
        }
        return RepeatStatus.FINISHED;
    }
```
The above was working for last 2 years with java 8. After i upgraded to java 11, i get the below error.
`javax.xml.stream.FactoryConfigurationError: No XMLValidationSchemaFactory implementation class specified or accessible (via system property 'org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c', or service definition under 'META-INF/services/org.codehaus.stax2.validation.XMLValidationSchemaFactory.w3c')
`

Am i missing something?

**Comment by pavan2017** [comment]
I missed adding msv-core dependency. Worked after adding it.

**Comment by pavan2017** [comment]
What is the compatible latest versions of woodstox-core-asl and stax2-api. I get 
java.lang.NoSuchMethodError: org.codehaus.stax2.ri.EmptyIterator.getInstance()Lorg/codehaus/stax2/ri/EmptyIterator;

When i use

 ```
<dependency>
            <groupId>org.codehaus.woodstox</groupId>
            <artifactId>stax2-api</artifactId>
            <version>4.2</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.woodstox</groupId>
            <artifactId>woodstox-core-asl</artifactId>
            <version>4.4.1</version>
        </dependency>
```

**Comment by cowtowncoder** [comment]
You can see compatible versions in `pom.xml` of Woodstox version itself. 
`woodstox-core-asl` 4.4.1:

https://mvnrepository.com/artifact/org.codehaus.woodstox/woodstox-core-asl/4.4.1

depends on `stax2-api` version `3.1.4`. Problem you see is probably #10.

You not need to explicitly include `stax2-api` as Woodstox has dependency, so leaving it out is usually a good idea (there may be exceptions if something else depends on older version).

I would upgrade to either `5.0.3` or `5.3.0`  as the first step:

```
<dependency>
    <groupId>com.fasterxml.woodstox</groupId>
    <artifactId>woodstox-core</artifactId>
    <version>5.3.0</version>
</dependency>
```

since 4.x is an old version and it might not work with Java 11. 6.x should, and I suspect 5.x is fine as well.

Note that although there are major version bumps, actual API is compatible and Java package names have not changed.
