### ISSUE TITLE
Woodstox 5.0.3 with Stax2-api 3.1.4 Cloud timeout exception

### ISSUE THREAD

**Issue by edwardUL99** [FasterXML/woodstox#118]
When parsing a large XML file I occasionally get this error:
The cloud operation was not completed before the time-out period expired.
I couldn't catch the exception type because debug wasn't enabled on my program when it happened. I remember it happening a lot before but I used WstxInputFactory.configureForXmlConformance and getConfig().doParseLazily(false). I then created the reader using createXMLStreamReader(File f). I thought it was fixed as it didn't happen in a while. But it happened again today. What could the problem be as I don't think this should be uploading anything to the cloud! 

It only appears to happen after editing and saving the file

**Comment by cowtowncoder** [comment]
Unfortunately this does not make it possible for me to reproduce the issue. Further, since Woodstox does not implement any timeout logic, i seems like it is something outside Woodstox triggering timeout, in which Woodstox has no control over it, nor would it seem like it would cause it.

So I would need a reproduction to help; or at very minimum a stack trace to something within Woodstox codebase to point that it is blocked on something.

**Comment by edwardUL99** [comment]
I think I resolved it. I stepped down into the exception trace and it was a FileInputStream throwing it. It turns out the file was in a folder being synced to OneDrive so it seems to have conflicted if the file was just saved and trying to sync with one drive while trying to parse it at the same time. The end product won't be using OneDrive synced folders so tested with files not in a synced folder and the exception did not get thrown. It was just the fact it was being thrown as a WstxLazyException that threw me. When I realised the IOException was being thrown by file input stream I knew it was a problem with the file and not Woodstox. So you can close this issue. Thanks anyway

**Comment by cowtowncoder** [comment]
@edwardUL99 Ok good! Thank you for the update.
