### ISSUE TITLE
Switch off XML Structure Validation using java properties

### ISSUE THREAD

**Issue by adilHamiani** [FasterXML/woodstox#158]
Hello,

I would like to know if it is possible to switch the flag CFG_VALIDATE_STRUCTURE to false using a java property
The only way to do this is to call method setProperty on WriterConfig or on WstxOutputFactory
but the issue is that a am calling an api org.apache.cxf.cxf-core-3-3-6 that calls woodstox api
and I could not manipulate the instance created of WstxOutputFactory

**Comment by cowtowncoder** [comment]
No, Java properties (and Environment variables) are a bad way to configure libraries and Woodstox does not support it. Problem is that such settings are global and would affect every and any usage within same JVM.
I mention just because the answer is "no" as well as "no, sorry, will not add".

So unfortunately this something where it is necessary for the framework to configure parser provider, or expose some means to do so (perhaps passing in pre-configured XMLOutputFactory).
