### ISSUE TITLE
Module `com.ctc.wstx` does not read a module that exports `com.ctc.wstx.shaded.msv.org_isorelax.verifier`

### ISSUE THREAD

**Issue by agavrilov76** [FasterXML/woodstox#193]
I'm getting the following error when running under JPMS (Java Modules) after upgrading 6.6.0

```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module com.ctc.wstx does not read a module that exports com.ctc.wstx.shaded.msv.org_isorelax.verifier
```

**Comment by cowtowncoder** [comment]
Hmmh. `relaxngDatatype` is included as shaded artifact, not as dependency. So I don't think there should be any module dependency. But I don't know what needs to change in module definition, generated using Modirect from

    src/moditect/module-info.java

This shouldn't have changed since 6.5.x; the only change that seems at all relevant is #182 (dependency update for `msv-core`).

So, I am not sure how to proceed here. All help would be appreciated!

**Comment by pjfanning** [comment]
This error occurred in Apache POI too. I had to revert the upgrade of woodstox.

**Comment by cowtowncoder** [comment]
It'd be good to resolve this, but I really do not know what change is needed: possibly the 4th and/or 5th `provides` clause from end of `src/moditect/module-info.java` that refers to shaded Factory/Factory loader. But it'd be good to have someone who could test it with a local build.

@pjfanning Do you think you could try this by just removing 2 entries after "//Include shaded in provisions", doing local build and trying resulting snapshot version?
If that works, I could release `6.6.1` with just that change.

**Comment by pjfanning** [comment]
@cowtowncoder the POI build worked ok with the 6.6.1 release - thanks

**Comment by cowtowncoder** [comment]
@pjfanning Thank you for confirming!

**Comment by cowtowncoder** [comment]
Would #200 be related here?
