### ISSUE TITLE
Content truncated when calling XMLStreamReader#getText() after CDATA event

### ISSUE THREAD

**Issue by elrodro83** [FasterXML/woodstox#22]
Although the fix for #21 works for the provided case, some slight modification to that test case causes it to fail. For instance, the following test fails:

```
  public void testLongerCData3() throws Exception {
    String SRC_TEXT =
        "123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678\r\n"
            + "<embededElement>Woodstox 4.0.5 does not like this embedded element.  However, if you take\r\n"
            + "out one or more characters from the really long line (so that less than 500 characters come between\r\n"
            + "'CDATA[' and the opening of the embeddedElement tag (including LF), then Woodstox will instead\r\n"
            + "complain that the CDATA section wasn't ended.";
    String DST_TEXT = SRC_TEXT.replace("\r\n", "\n");
    String XML = "<?xml version='1.0' encoding='utf-8'?>\r\n"
        + "<test><![CDATA[" + SRC_TEXT + "]]></test>";
    XMLInputFactory f = getInputFactory();
    // important: don't force coalescing, that'll convert CDATA to CHARACTERS
    f.setProperty(XMLInputFactory.IS_COALESCING, Boolean.FALSE);

    XMLStreamReader sr = f.createXMLStreamReader(new StringReader(XML));
    assertTokenType(START_DOCUMENT, sr.getEventType());
    assertTokenType(START_ELEMENT, sr.next());
    assertEquals("test", sr.getLocalName());
    assertTokenType(CDATA, sr.next());
    // This should still work, although with linefeed replacements
    final String text = sr.getText();
    if (text.length() != DST_TEXT.length()) {
      fail("Length expected as " + DST_TEXT.length() + ", was " + text.length());
    }
    if (!text.equals(DST_TEXT)) {
      fail("Length as expected (" + DST_TEXT.length() + "), contents differ:\n" + text);
    }
    assertTokenType(END_ELEMENT, sr.next());
    sr.close();
  }
```

The only difference with testLongerCData2 is that this one does not contain a line break at the beginning of the numbers sequence. Running this test results in a failure with message `junit.framework.AssertionFailedError: Length expected as 829, was 73`.

Just in case, another similar test case with no line breaks at all should be included.

**Comment by cowtowncoder** [comment]
Rats. 

Thank you for digging through this, will try to resolve too.

**Comment by elrodro83** [comment]
Hi @cowtowncoder , were you able to take a look at this?

**Comment by cowtowncoder** [comment]
Hmmh. Actually... I am not sure this (or #20 come to think of that) is an actual bug: it depends on whether specification requires coalescing all contents of a CDATA segment into a single event, unlike with CHARACTERS (which may be reported as multiple segments).
What happens here is simply that while the first CDATA event you get only contains part of the physical segment, iterating via `XMLStreamReader.next()` will return more CDATA events with more of contents.
This is intentional in that it allows access to all data, but without forcing buffering of all of it in memory.

It has been a while since I wrote Woodstox, but as I recall this is intentional; and to force coalescing, you do need to enable `XMLInputFactory.IS_COALESCING`.

There is also Woodstox configuration property `WstxInputProperties.P_MIN_TEXT_SEGMENT` (default value: 64) which you can increase to get behavior you want (always report full CDATA events; although also applies to CHARACTERS) -- just set that to `Integer.MAX_VALUE`.
In this particular case you would be getting first `73` characters as something just slightly about minimum of 64 characters.

**Comment by elrodro83** [comment]
Hi @cowtowncoder ,

I have created an issue/PR against (https://issues.apache.org/jira/browse/CXF-7058 and https://github.com/apache/cxf/pull/169) CXF to allow them to pass the `WstxInputProperties.P_MIN_TEXT_SEGMENT` parameter as you mentioned.

Thanks for your insight!
