### ISSUE TITLE
Maximum XML name limit not applied to namespace URIs (JAXP, 8148872)

### ISSUE THREAD

**Issue by provash** [FasterXML/woodstox#24]
CVE-2016-3500 OpenJDK: maximum XML name limit not applied to namespace URIs (JAXP, 8148872)

I have found the issue in woodstox-core-asl-4.0.8.jar. I have produced this issue with huge namespace URL.
java.lang.OutOfMemoryError: Java heap space
              at com.ctc.wstx.util.TextBuilder.resize(TextBuilder.java:179)
              at com.ctc.wstx.util.TextBuilder.bufferFull(TextBuilder.java:151)
              at com.ctc.wstx.sr.BasicStreamReader.parseNormalizedAttrValue(BasicStreamReader.java:1912)

Please let me know whether this issue is fixed in 5.0.3 release.

**Comment by cowtowncoder** [comment]
@provash Where would such a limit be defined? I was not aware of limits. Note that in general content limitations against DoS attacks were added in later 4.x versions (4.4.1 would have them), but this uses Woodstox-specific set of properties as I was not aware that JAXP specified any properties.

So I would need to know where JAXP specification defines additional property names that could be used: Stax API does not (or at least did not) define any originally.

**Comment by provash** [comment]
@cowtowncoder I was exploring the JAXP issue in STAX implementation (Woodstox ) to verify how it handle this  issue. But I saw it throws java heap space exception. 

I have analysis the latest code in github repo for parseAttrValue(char openingQuote, TextBuilder tb). But as per my understanding latest version also not handled this vulnerability. https://github.com/FasterXML/woodstox/blob/master/src/main/java/com/ctc/wstx/sr/BasicStreamReader.java

JAXP has property "maxXMLNameLimit", which is used to limit the maximum size of XML names, including element name, attribute name and namespace prefix and URI
https://docs.oracle.com/javase/tutorial/jaxp/limits/limits.html

**Comment by cowtowncoder** [comment]
@provash there are two separate things: one is about kinds of limits Woodstox supports (implemented before JAXP had such limits, or at least before I became aware of existence), and the other about mapping property ids so that both Woodstox native ids (originally added) and JAXP ones are supported.

Work for mapping existing limits to new alternate ids is of course much easier; adding support for new limits is more difficult. You are probably right in that there is no support currently for limiting length of attribute or element names, since these do/did not seem like primary attack vectors as you still need to send huge documents to trigger issues. But after other limits have been implemented (for nesting, entity expansion, text segments), adding these probably would also make sense.

**Comment by provash** [comment]
I have seen that validation  code is added in latest 5.0.5 version. https://github.com/FasterXML/woodstox/blob/master/src/main/java/com/ctc/wstx/sr/BasicStreamReader.java 

So I am closing this issue.

**Comment by rakeshsrinivasa** [comment]
When you reach the maximum limit of an attribute.The following exception message is thrown

Caused by: javax.xml.stream.XMLStreamException: Maximum attribute size limit (524288) exceeded
	at com.ctc.wstx.sr.StreamScanner.constructLimitViolation(StreamScanner.java:2478)
	at com.ctc.wstx.sr.StreamScanner.verifyLimit(StreamScanner.java:2471)
	at com.ctc.wstx.sr.BasicStreamReader.parseAttrValue(BasicStreamReader.java:2034)

--> By Default the maximum attribute size limit is 524288

Thanks 
Rakesh

**Comment by cowtowncoder** [comment]
@rakeshsrinivasa Yes, and.... ?
