### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by zerok** [FasterXML/woodstox#25]
Hi 😃 

I was just looking through this repository for some license information and noticed that quite a few source files have the following header:

```
/* Woodstox XML processor
 *
 * Copyright (c) 2004- Tatu Saloranta, tatu.saloranta@iki.fi
 *
 * Licensed under the License specified in the file LICENSE which is
 * included with the source code.
 * You may not use this file except in compliance with the License.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
```

This refers to a LICENSE file which I couldn't find anywhere in the repository. What is the license of this project and could you perhaps create the missing LICENSE file? Thanks!

**Comment by cowtowncoder** [comment]
I'll try to improve information; typically it'd be found from `pom.xml`, under `src/main/resources` and from project Wiki.

License is Apache License 2.0.

**Comment by zerok** [comment]
Awesome, thanks :) Quite a few projects also simply have a LICENSE(.txt) file in the root folder of the repository. I guess that was also the case here at some point but got lost during moves from one SCM to the next or something like that.

**Comment by cowtowncoder** [comment]
No, not really, it's just that for DRY, existence of `src/main/resources/LICENSE` (needed to make sure it gets included in binary and source jars), another copy of LICENSE seemed unnecessary.
Unfortunately I can see benefits of root-level inclusion, since other tools auto-detect that and not Maven structure... 

But given that it's just a one-time thing, maybe I should indeed just copy the license and allow tiny bit of replication for convenience :)

**Comment by zerok** [comment]
Awesome, thank you :-)
