### ISSUE TITLE
StreamReader reads incomplete CDATA 

### ISSUE THREAD

**Issue by TomasHofman** [FasterXML/woodstox#26]
In some cases, CDATA content returned by ValidatingStreamReader is not complete.

I created a simple reproducer. When woodstox dependency is commented out, it passes. With woodstox it fails.

https://github.com/TomasHofman/woodstox-reproducer

**Comment by cowtowncoder** [comment]
Ok. And just to make sure -- since you are not specifying that coalescing mode is enabled, nor changed minimum segment to report -- do you not get all the contents at all? Woodstox may split both regular text and CDATA segments into smaller chunks.
Although I thought that for validation purposes it would try not to split contents for simplicity of validation (so validator would have less state to keep).

**Comment by TomasHofman** [comment]
Meh, just figured it out - data are truncated into several chunks. My bad... I'm closing the issue.

**Comment by TomasHofman** [comment]
Thanks for help in any case!

**Comment by cowtowncoder** [comment]
@TomasHofman No problem; I had forgotten about this myself, and had to actually go back and check it out... there are 2 ways to prevent splitting; one is to enable coalescing mode (which then combines all segments); the other to set Woodstox-specific setting that specifies minimum length of text segment that may be returned (except for full segment of course), but will not combine adjacent text with CDATA.
