### ISSUE TITLE
Method XMLStreamWriter.writeCharacters(String) escape '>'  char only at the start of a string

### ISSUE THREAD

**Issue by arisjramos** [FasterXML/woodstox#41]
Example OK : 
`// will print <DATA>&gt; test &amp;</DATA>`
```
ByteArrayOutputStream output=new ByteArrayOutputStream();
Charset charset = StandardCharsets.ISO_8859_1;
XMLOutputFactory xmlFactory = javax.xml.stream.XMLOutputFactory.newInstance();
XMLStreamWriter writer = xmlFactory.createXMLStreamWriter(output, charset.name());
writer.writeStartElement("DATA");
writer.writeCharacters("> test &");
writer.writeEndElement();
writer.close();
System.out.println(output.toString(charset.name()));
```

Example NOT OK : 
`//will print "<DATA>&amp; test ></DATA>"` 

```
ByteArrayOutputStream output=new ByteArrayOutputStream();
Charset charset = StandardCharsets.ISO_8859_1;
XMLOutputFactory xmlFactory = javax.xml.stream.XMLOutputFactory.newInstance();
XMLStreamWriter writer = xmlFactory.createXMLStreamWriter(output, charset.name());
writer.writeStartElement("DATA");
writer.writeCharacters("& test >");
writer.writeEndElement();
writer.close();
System.out.println(output.toString(charset.name()));
```

**Comment by cowtowncoder** [comment]
What is the bug here? `>` is not required to be escaped as per XML specification, except for one very specific case: sequence `]]>` is not allowed to be included unescaped. In all other cases it may or may not be escaped: this makes no difference to xml parsers. Woodstox ensures that this happens; in case of beginning of string it may not be possible to if sequence ']]' was output prior to write call (since it is legal to call `writeCharacters()` multiple times); in latter case content can be checked to see if there is need.

**Comment by arisjramos** [comment]
You are right, I tested with jdk and it escaped all the '>' chars it misleaded my jugement., 
It is true that '>' is a legal character but the specification strongly recommends to escape it.... sorry

**Comment by cowtowncoder** [comment]
No bug to fix here. I don't recall strong recommendation, and while I understand some users might prefer such behavior I don't have much interest in changing behavior here.

Not... there is a way to change escape settings, by registering `TextEscaper` (via `EscapingWriterFacotry`):

http://fasterxml.github.io/woodstox/javadoc/5.0/com/ctc/wstx/api/WriterConfig.html#setTextEscaperFactory(org.codehaus.stax2.io.EscapingWriterFactory)

I didn't immediately find unit test that exercises it, but this facility does allow customizing all aspects of output. It's quite a bit of work but possible to make work.

**Comment by cowtowncoder** [comment]
Actually, configuration property is briefly covered here:

https://medium.com/@cowtowncoder/configuring-woodstox-xml-parser-stax2-properties-c80ef5a32ef1

but funnily enough there's no unit test for it. I think I might want to write one... I must have verified its functioning somehow since I wrote the feature :)

**Comment by cowtowncoder** [comment]
And here are rudimentary tests that show usage:

https://github.com/FasterXML/woodstox/commit/393597c9a4cf5b3545288227ab4000b091739efd
