### ISSUE TITLE
Security problem when using Woodstox as a drop-in replacement for JDK parsers

### ISSUE THREAD

**Issue by veita** [FasterXML/woodstox#50]
_[JEP 185](http://openjdk.java.net/jeps/185): Restrict Fetching of External XML Resources_ introduced system properties for securing applications against security threats such as [XML External Entities](https://www.owasp.org/index.php/Top_10-2017_A4-XML_External_Entities_(XXE)).

When e.g. the system property `-Djavax.xml.accessExternalDTD=` is set to the empty list, the JDK parsers throw an exception if the parsed document contains a reference to an external DTD.

When Woodstox is added to the application's class path it replaces the default parsers. But then the system property seems no longer to have any effect, weakening the security of the application.

Since security is generally a major concern Woodstox should honour the properties introduced by JEP 185.

**Comment by cowtowncoder** [comment]
Why would you use this system property instead of Stax standard property

   `XMLInputFactory.IS_SUPPORTING_EXTERNAL_ENTITIES`

? Disable that (using `factory.setProperty()`) and things work as expected.

Since this property seems to be relatively need addition, Woodstox does not yet support it. No one has so far requested its addition.

But I will file an issue for adding support.

**Comment by cowtowncoder** [comment]
Created #51 as placeholder so that whoever has time can work on it.

**Comment by cowtowncoder** [comment]
@veita forgot to add the important part: Thank you for reporting this.

I hope we can update things to support newer Oracle additions, even if communication lines do not always seem to work well (we used to get more patches, updates, from them, couple of years ago).
