### ISSUE TITLE
weblogic 10 and weblogic 12 in relation to XMLInputFactory implementation long text value get truncated

### ISSUE THREAD

**Issue by alanmehio** [FasterXML/woodstox#68]
The default implementation for weblogic 10 for XMLInputFactory implementation is 
weblogic.xml.stax.XMLStreamInputFactory

While the default implementation for JRE 8  for XMLInputFactory implementaiton is 
com.sun.xml.internal.stream.XMLInputFactoryImpl

Now in weblogic 12, the default implemetation for XMLInputFactory  implementation is 
com.ctc.wstx.stax.WstxInputFactory

The issue we have encountered is weblogic 10 and Junit parse and obtain a lenghty content of an xml file  while in weblogic 12, the content get truncated and we thing is due to the XMLStreamReader of the WstxInputFactory which is com.ctc.wstx.sr.ValidatingStreamReader 
We have not following  the weblogic 10 XMLStreamReader but we can do that later. In JRE8 it is 
com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl

We can send you more details about the issue with a junit test to replictate if required. In summary if the xml content retrieved from org.jaxen.BaseXPath#selectSingleNode(Object node); ( jaxen-1.1.6.jar) the value get truncated.

Regards,
Alan Mehio

**Comment by alanmehio** [comment]
Dear All, 
It may be not an issue but rather a parsing configuraiton properties. I have mentioned lengthy xml content 
I was looking att your implementation class WstxInputFactory for xml Reading and it mentions the class  WstxInputProperties in the factory  xml Reading using stax parsing  the following
"Second, there are additional properties, defined in  constant class link WstxInputProperties.
I have looked at this class constant WstxInputProperties" and I have found this property
public final static String P_INPUT_BUFFER_LENGTH = "com.ctc.wstx.inputBufferLength";
Can you please elaborate on this?
Thanks

**Comment by cowtowncoder** [comment]
@alanmehio no, buffer length should not be the key here (although for performance optimizations it might be useful).

But unless your code handles possibly separate text segments, you will want to enable this feature:

https://docs.oracle.com/javase/8/docs/api/javax/xml/stream/XMLInputFactory.html#IS_COALESCING

since otherwise document like:

```xml
<root>Some textual
  content
</root>
```

may be returned so that there are more than 1 `CHARACTERS` segment: text is NOT guaranteed to be returned in just one event. I have had many developers report a bug due to this since some parsers handle segmentation differently (some base it on linefeeds, others on input buffer boundaries; some never split segments).

**Comment by alanmehio** [comment]
Reverted back to use weblogic 10 jar library which sort the issue.
