### ISSUE TITLE
com.ctc.wstx.sr.CompactNsContext#doGetNamespaceURI() returns null on missing prefix (instead of "")

### ISSUE THREAD

**Issue by pdvrieze** [FasterXML/woodstox#8]
According to the documentation of [`NamespaceContext`](http://docs.oracle.com/javase/7/docs/api/javax/xml/namespace/NamespaceContext.html), an unbound prefix should result in the [`XMLConstants.NULL_NS_URI`](http://docs.oracle.com/javase/7/docs/api/javax/xml/XMLConstants.html#NULL_NS_URI) being returned on invoking [`getNamespaceURI`](http://docs.oracle.com/javase/7/docs/api/javax/xml/namespace/NamespaceContext.html#getNamespaceURI%28java.lang.String%29). The implementation returns `null` instead. This is visible on line 90.

**Comment by cowtowncoder** [comment]
With version... ?

**Comment by pdvrieze** [comment]
The version I used is 5.0.1, but the issue is also in the current master.

**Comment by cowtowncoder** [comment]
Since this changes observed behavior (which has been there since Woodstox 1), this can't be done in a patch. Probably could go in 5.1, however, given that it is a deviation of Stax javadocs.
The initial choice was based on earlier more vague/ambiguous definition (from the original Stax specification) which didn't (I think) specify value to use. I assume most client code has to consider either `null` or empty String likely, due to historical reasons.

**Comment by pdvrieze** [comment]
Since filing this I have done a lot of further work with the parser and namespace contexts. This involves sub-documents and general xml processing (not just as a serialization format). Effectively there is, in those non-straightforward cases, a strong case to returning null in the absent case as there are cases where the presence or absence of a declaration itself is of significance.

Looking at it this way, it may be the best way forward to document the behaviour carefully and also perhaps make it possible to toggle the behaviour with a feature. Unfortunately the Java XML api's are a bit of a mess and this is not nearly the worst part of it.

**Comment by cowtowncoder** [comment]
@pdvrieze Yes. My original interpretation was indeed due to what I thought made sense to distinguish "not bound" from possible explicit "empty namespace". However, given that no prefix other than no/empty prefix (that is, the default prefix used if none specified) is allowed to bind to URI of "", this may or may not be necessary distinction.

I also fully agree in messiness: original Stax API was rather under-specified, and although there have some gradual clarifications (... sometimes via implications in javadocs, but not necessarily spec).

So at this point let's leave things as-is: I will leave the issue open for now so that there is visibility should anyone else come looking.

**Comment by cowtowncoder** [comment]
Forgot to add one related piece:

    WstxInputProperties.P_RETURN_NULL_FOR_DEFAULT_NAMESPACE

(which still defaults to `false`, was meant to go in 5.0)

allows changing of this behavior.

**Comment by cowtowncoder** [comment]
Clarification for above: `WstxInputProperties.P_RETURN_NULL_FOR_DEFAULT_NAMESPACE` exists (since 4.1.2), and it can be changed to affect behavior.

Further... looks like it defaults to `false`, which means that as far as I can see, "" is returned now, not null. This as of 5.0.3.
If not, a reproduction to show otherwise would be good.

**Comment by cowtowncoder** [comment]
Actually, one more thing: tests that exist exercise namespace URI access differently.
So I can not reproduce the issue. But it is possible that other access methods would show it.

A reproduction would be needed; until then, closing.
