### ISSUE TITLE
What are the pr* releases?

### ISSUE THREAD

**Issue by veita** [FasterXML/woodstox#81]
Our QA builds fail because of Maven metadata announced `6.0.0.pr1` and `6.0.0.pr2` as new Woodstox versions.

However, I suspect that these versions are not actually release versions as stated in http://central.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/maven-metadata.xml

**Comment by cowtowncoder** [comment]
They would be Pre-Releases (sometimes known as Release Candidates). While I have not used this mechanism much with Woodstox (due to maturity of the project), I am doing it now because I am not 100% sure Java module info being added is yet correct, and want to get it verified by others before doing official 6.0.0 release.
So bit similar to snapshots, except that they are available from regular Maven (Central) repository, for evaluation purposes.
